version: "3.5"

networks:
  primary:
    name: primary
    driver: bridge

services:
  db:
    container_name: tlcbot2-db
    build: 
      context: ./.docker/postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME

  bot:
    container_name: tlcbot2
    build:
      context: TLCBot2
    env_file:
      - .env
    volumes:
      - ./TLCBot2:/opt/app
